Develop
mageworx/MageWorx_MultiFeesGraphQl pull request #1
Opened 2022-06-09 14:52 UTC by mkostevich

2022-06-20 16:05 UTC, SiarheyUchukhlebau requested changes

2022-06-20 16:05 UTC, SiarheyUchukhlebau commented on Model/Resolver/Cart/AbstractAppliedFees.php
> +    protected function getPreparedOprions(array $options, string $currencyCode): array
Typo: `getPreparedOprions` must be `getPreparedOptions`

2022-06-20 16:05 UTC, SiarheyUchukhlebau commented on etc/schema.graphqls
> +    mw_applied_product_fees: [MwAppliedProductFee] @doc(description: "Applied Product Fees") @resolver (class: "\\MageWorx\\MultiFeesGraphQl\\Model\\Resolver\\Cart\\AppliedProductFees")
Move `MwAppliedProductFee` from the `Cart` level to the `CartItem` level.

2022-06-21 09:49 UTC, mkostevich commented on Model/Resolver/Cart/AbstractAppliedFees.php
> +    protected function getPreparedOprions(array $options, string $currencyCode): array
done

2022-06-21 09:49 UTC, mkostevich commented on etc/schema.graphqls
> +    mw_applied_product_fees: [MwAppliedProductFee] @doc(description: "Applied Product Fees") @resolver (class: "\\MageWorx\\MultiFeesGraphQl\\Model\\Resolver\\Cart\\AppliedProductFees")
done.

2022-06-21 11:31 UTC, SiarheyUchukhlebau approved these changes

2022-08-03 11:54 UTC, merged